### ISSUE TITLE
Logo does not look very sharp

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/LessonsApp#123]
On this https://lessons.church/login Page the logo seems blurry

**Comment by PhotoPaul** [comment]
Who can provide a higher resolution logo? This one is only 253 x 45 px and we need one that's at least 350 × 62px.

**Comment by mbyrdLCS** [comment]
![Horizontal2](https://user-images.githubusercontent.com/65249159/167943960-1a2c4464-e902-4c0e-8900-1a92ae6c3ba7.png)
![Horizontal](https://user-images.githubusercontent.com/65249159/167943992-158ba5fc-6f27-4fd6-82d0-2708d0e894cf.png)
![Vertical](https://user-images.githubusercontent.com/65249159/167944027-bddeded0-c029-4308-bdab-8263058c0bee.png)

This is what I have hope it helps

**Comment by PhotoPaul** [comment]
I pushed a higher resolution logo and updated the login screen to point to it. Someone now needs to push this to Production. Is that someone you @jzongker ?

**Comment by jzongker** [comment]
Sorry I didn't see this.  Yes it is.  Deployed. :-)
