### ISSUE TITLE
Admin page has sizing issue

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/LessonsApp#129]
<img width="1392" alt="Screen Shot 2022-03-06 at 4 57 35 PM" src="https://user-images.githubusercontent.com/65249159/156946034-366b4222-5925-483e-83f3-a1c3e772854c.png">

**Comment by jzongker** [comment]
In addition to adding Variants and Assets to a Resource, this also occurs when adding a new Section to a Venue.  The popup modal should be able to freely extend beyond the bounds of it's parent div.  Perhaps just a postion:absolute on the css?

![image](https://user-images.githubusercontent.com/1447203/169717775-435ed793-ee0a-41ef-8214-4f169b1c3641.png)
![image](https://user-images.githubusercontent.com/1447203/169717778-bf8130ff-a591-46f9-b163-ae23681e518c.png)

**Comment by PhotoPaul** [comment]
https://github.com/LiveChurchSolutions/LessonsApp/commit/46ae935e08d18cd913a2cc8e5cd13e856328497c and https://github.com/LiveChurchSolutions/LessonsApp/commit/b56ce43a86cd9f43b2b920ceadaad03196682ba3
