### ISSUE TITLE
Error when adding Section

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/LessonsApp#149]
![Screen Shot 2022-06-03 at 7 25 44 AM](https://user-images.githubusercontent.com/65249159/171853507-fba234a0-021e-4513-906f-36032171b241.png)

**Comment by mbyrdLCS** [comment]
same error when adding an asset:
![Screen Shot 2022-06-03 at 7 52 42 AM](https://user-images.githubusercontent.com/65249159/171857896-673562b2-414e-41e4-914e-7de837cd98de.png)

**Comment by PhotoPaul** [comment]
I'm sorry @mbyrdLCS but I thought this was fixed:

![image](https://user-images.githubusercontent.com/3471804/172109729-1392f509-3434-4cf7-8339-d91e23025e24.png)
![image](https://user-images.githubusercontent.com/3471804/172109779-92de7947-d96a-4dbd-89f2-7cfb90971657.png)

@jzongker Maybe the fix hasn't been pushed to production yet?
