### ISSUE TITLE
Error when adding a new program

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/LessonsApp#150]
The providerId field is not being populated on when new programs are added.  Need to ensure that it is.

**Comment by PhotoPaul** [comment]
There doesn't seem to be any relevant field on the form, so how do you want to handle it?
Do you want to add a drop down with the providers from the `providers` table?

![image](https://user-images.githubusercontent.com/3471804/172114018-44c93702-da3d-4690-b0ab-baf9efd22103.png)

**Comment by PhotoPaul** [comment]
@jzongker  There doesn't seem to be any relevant field on the form, so how do you want to handle it?
Do you want to add a drop down with the providers from the `providers` table?

![image](https://user-images.githubusercontent.com/3471804/172114018-44c93702-da3d-4690-b0ab-baf9efd22103.png)

**Comment by jzongker** [comment]
There is a 1:1 relationship between a provider in the lessons database and a church in the access database.  Just look up which provider is associated with the currently logged in church and auto-assign it rather than add any input.

**Comment by PhotoPaul** [comment]
https://github.com/LiveChurchSolutions/LessonsApi/commit/05df2ee4378384bdf280c8159fbc3ba0515f102c
