### ISSUE TITLE
User menu is not dismissable

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/LessonsApp#155]
For some reason the user menu wouldn't work when setting the menuAnchor to the actual link, so I set it to the navBar instead.  That caused the position of the menu to be off so I "fixed" it with marginRight and marginTop.  When setting those properties it's impossible to dismiss the menu once it's open.  We need to find a better solution.

![image](https://user-images.githubusercontent.com/1447203/173905279-efd90c7c-495b-4e4f-b1a9-833080ae1a9d.png)

**Comment by PhotoPaul** [comment]
Hope that's ok https://github.com/LiveChurchSolutions/LessonsApp/commit/b2eb56ae680ddf5436b2de0497b62035a87b5f62
(judging by the screenshot, you may want to increase the "top" style)
