### ISSUE TITLE
 I added a section, and tried to add the top assert and it didn’t load. 

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/LessonsApp#164]
![image_67130625](https://user-images.githubusercontent.com/65249159/176315221-c9d418be-0bcd-4970-9dcc-2c0149356f8d.JPG)

Top assets do not work

**Comment by jzongker** [comment]
Fixed with https://github.com/LiveChurchSolutions/LessonsApp/commit/f641bea8078817f89f2d8d3a88970fe759049a5d
