### ISSUE TITLE
Lessons.Church Stats Map

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/LessonsApp#174]
The Map is having trouble loading on the admin page of lessons.church Stats. 

This Pick is from the Ark admin page 
<img width="1008" alt="Screen Shot 2022-07-15 at 6 41 38 AM" src="https://user-images.githubusercontent.com/65249159/179208080-ef5e69e0-391a-4ed6-92a0-835c7ef816f9.png">

**Comment by jzongker** [comment]
Fixed in #176 .  The hosted copy of the globe geometry went offline.  Pointed to a self-hosted copy instead.
