### ISSUE TITLE
. at the end of the password on lessons.church 

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/LessonsApp#207]
when you signup you get a temp password would it be possible to take the period out after the end of the password? Also is it possible to make that email look a little more inviting and possibly add the new video in it? 

https://youtu.be/DmDcQr0IfJg

**Comment by jzongker** [comment]
The user registration email now looks like this (title varies by app).  
![image](https://user-images.githubusercontent.com/1447203/187536719-57afadc4-042a-49c3-8506-f378b95f3bd2.png)
