### ISSUE TITLE
Admin page does not open up for new lessons correctly

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/LessonsApp#224]
When adding a new lesson you have to cancel everything out before adding a new lesson. 

https://user-images.githubusercontent.com/65249159/193428773-cf3aa822-c0f3-45c9-918d-56cb84b7c884.mp4

**Comment by PhotoPaul** [comment]
Seems like there are additional warnings in this page, but this should do it for now.
https://github.com/LiveChurchSolutions/LessonsApp/commit/6065e07f670a4ad161286f53cb5312dad58a8b60
