### ISSUE TITLE
Add App Promo to Downloads Menu

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/LessonsApp#225]
When a user clicks the download button on a lesson and gets this popup, add a message to the bottom promoting the Lessons.church TV app.   Something along the lines of

_**Don't want to download lessons each week?**

Get the Lessons.church app for AndroidTV or FireSticks and your videos and slides will automatically be downloaded each week based on the schedule you set up.  [Learn how](https://lessons.church/#connectSection)._

![image](https://user-images.githubusercontent.com/1447203/196551140-fedfa81f-2084-4e46-8f2f-25489f5a84f2.png)

**Comment by PhotoPaul** [comment]
@jzongker I played around with it and it's way too much text.
![image](https://user-images.githubusercontent.com/3471804/196728308-1999282c-dbe4-4279-ac90-50495d7e6f42.png)

Can I just keep the title and the button and remove the description?

**Comment by PhotoPaul** [comment]
https://github.com/LiveChurchSolutions/LessonsApp/commit/6b65592f65679affac56f6c9caf2b758235699e7 & https://github.com/LiveChurchSolutions/LessonsApp/commit/8cc332bb5598914f00f49f690dc958c3be9327bc
