### ISSUE TITLE
[Cosmetic Issue] Incorrect Spelling on one Lesson under Ark Kids Elementary > Don't Fear

### ISSUE THREAD

**Issue by luisagloria** [LiveChurchSolutions/LessonsApp#226]
#### Issue description
Incorrect Spelling on one Lesson under Ark Kids Elementary > Don't Fear

#### Prerequisites
URL: https://staging.lessons.church/ (also reproduced on lessons.church live app)
Browser: Chrome

#### Steps to reproduce the issue

1.  Go to the prerequisite listed above
2. Navigate to Ark Kids Elementary > Don't Fear study
3. Check on first lesson's title

#### What's the expected result?
Title should be _Don't Fear, Jesus is Strong!_

#### What's the actual result?
Title should be _Dont't Fear, Jesus is Strong!_

#### Additional details / screenshot
![image](https://user-images.githubusercontent.com/101709075/197139523-042df9f4-f71e-47d8-9306-c08c12458148.png)
![image](https://user-images.githubusercontent.com/101709075/197140332-7fdb5945-6831-4cc5-84d0-3784ce62856b.png)

**Comment by mbyrdLCS** [comment]
Thank You this has been fixed.
