### ISSUE TITLE
Preview box/dialog of videos hosted on Vimeo in Lessons is not working (staging env)

### ISSUE THREAD

**Issue by luisagloria** [LiveChurchSolutions/LessonsApp#227]
#### Issue description
Preview box/dialog of videos hosted on Vimeo in Lessons is not working (staging env)

#### Prerequisites
URL: https://staging.lessons.church/ (not reproducible in lessons.church live app)
Browser: Chrome

#### Steps to reproduce the issue

1.  Go to the prerequisite listed above
2. Navigate to any lesson (ex: Ark Kids Elementary > Don't Fear > Don't Fear, Jesus is Strong lesson)
3. Expand on lesson details and find a link/video hosted on Vimeo

#### What's the expected result?
A Preview box/dialog should appear 
<img width="593" alt="image" src="https://user-images.githubusercontent.com/101709075/197145621-a0a8920c-8337-4f95-a600-3b2cf5f1cfa5.png">

#### What's the actual result?
Nothing happens upon clicking the link/video hosted on Vimeo

**Comment by PhotoPaul** [comment]
Fixed 6edcf142938c9326604b3e9e4571dd987d21e261
