### ISSUE TITLE
Custom error page

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/LessonsApp#49]
It's hard to track down the cause of errors with the nextjs version of the app.  Add a custom error page that's simple looking for users but provides the ability to see the actual error message.  It can show up in the console log or an expandable link.

**Comment by matt2695** [comment]
@jzongker is [this](https://nextjs.org/docs/advanced-features/error-handling)  what you are expecting for this enhancement or do you have something more specific in mind?

**Comment by jzongker** [comment]
Yeah, the custom pages/500.js from the article you linked.  Just show the site wrapper with some kind of pretty "Uh oh, an error has occurred" type message.  Ideally with a collapsible box to view the error details.
