### ISSUE TITLE
Add Google Analytics tracking

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/LessonsApp#52]
Implement "react-ga" within the app to track pageviews and signups via google analytics.  Here's how it's done in StreamingLiveWeb as an example, but it'll be a bit different in NextJs

https://github.com/LiveChurchSolutions/StreamingLiveWeb/blob/main/src/Routing.tsx
https://github.com/LiveChurchSolutions/StreamingLiveWeb/blob/main/src/Login.tsx
https://github.com/LiveChurchSolutions/StreamingLiveWeb/blob/main/src/helpers/EnvironmentHelper.ts

**Comment by jzongker** [comment]
Let's add a conditional check to make sure the analytics tag is actually stored in the environment variable before rendering the GA scripts.

Ideally, let's get this helper class to follow the same naming conventions as the others as well.

**Comment by pranavmalvawala** [comment]
Interesting, the code should have picked up the tag, it worked fine in local that's why I even deployed.

**Comment by pranavmalvawala** [comment]
So the real problem was google analytics env key was missing in vercel envs, I've added it and it works
