### ISSUE TITLE
Make static pages load "instantly"

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/LessonsApp#6]
Lessons.church host a lot of database driven pages that are mostly static (they update rarely).  Currently these pages show a "loading..." message for 1-5 seconds.  We need to eliminate that loading message.  

Example pages:

- https://lessons.church/
- https://lessons.church/programs/yBl-EUBxm17
- https://lessons.church/studies/jVnaEo5LIz0
- https://lessons.church/lessons/dQbnqKnqOK0

There are likely multiple ways to do this, but NextJS with Incremental Static Regeneration looks like a great approach.  I would very much so like to keep this a serverless app which looks like it's possible with https://www.serverless.com/blog/serverless-nextjs .

Look into this and try to make/deploy (to staging) an initial build as a nextjs project.

**Comment by jzongker** [comment]
The urls have changed now to more seo-friendly paths.  The example pages are now:

- Home page https://lessons.church/
- Program page https://lessons.church/high-voltage/
- Study page https://lessons.church/high-voltage/family-mechanics
- Lesson page https://lessons.church/high-voltage/family-mechanics/family-feud/

**Comment by pranavmalvawala** [comment]
Whole app is converted to Nextjs so I believe this can be closed now.
