### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/LessonsApp#73]
When Logging in it is suppose to give you the popup to choose a church when it does everything works great however I usually have to login 2 times no matter which account I am using because the first time there is no popup and I don't have the option to use schedules.  I log out and when I log back in I get the pop up and everything works fine.

**Comment by pranavmalvawala** [comment]
That's interesting, I tried many times it always works (schedules item shows in popup). If can drop in steps and or some specific scenario when this happens it'd be great.

**Comment by mbyrdLCS** [comment]
Last couple times I have logged in it has worked great if I see the issue again I will try to report exactly the steps that I did to get the error.

**Comment by pranavmalvawala** [comment]
Yes, that'd be great!

**Comment by jzongker** [comment]
Going to close this issue for now.  If it recurs we can re-open it.
