### ISSUE TITLE
Play File in SP without letting people download it on the Site 

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/LessonsApp#97]
With Big Big Worship giving us there songs for free I would like to make it to where you would not be able to download those songs on lessons.church but when you put the feed in SP the worship songs worked. Do we have the ability to hide something we play in the feed?

**Comment by jzongker** [comment]
There is already a hidden field for variants in the admin that's used for files that shouldn't show up in the download list (webms).  It can achieve this purpose, but let's discuss on Slack first.
